In [2]:
import pandas as pd
import numpy as np 
from sklearn.preprocessing import OneHotEncoder

In [3]:
link = '/Users/maxkucher/preprocessing/mlops/income/data.csv'
data = pd.read_csv(link)
data

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [4]:
data["income"].unique()
data['income'] = data['income'].replace({'<=50K': 0, '>50K': 1})
data

/var/folders/tl/sxyv3tjs7wlff0fs8dht26pr0000gn/T/ipykernel_27185/3799369842.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['income'] = data['income'].replace({'<=50K': 0, '>50K': 1})

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,0
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,0
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,0
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,0
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,0
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0

In [5]:
data.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education.num     0
marital.status    0
occupation        0
relationship      0
race              0
sex               0
capital.gain      0
capital.loss      0
hours.per.week    0
native.country    0
income            0
dtype: int64

In [6]:
# data.loc[2, "workclass"]

In [7]:
data['workclass'].unique()
data['workclass'] = data['workclass'].replace({'?': 'Unkown'})
data

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,Unkown,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,0
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,0
2,66,Unkown,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,0
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,0
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,0
32557,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,0
32558,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,1
32559,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,0
32560,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,0

In [8]:
encoder = OneHotEncoder(handle_unknown = 'ignore', sparse_output = False)

encoded = encoder.fit_transform(data[['workclass']])

encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['workclass']), index=data.index)

data = pd.concat([data.drop('workclass', axis="columns"), encoded_df], axis='columns')

data

,age,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,...,income,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Unkown,workclass_Without-pay
0,90,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,82,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,66,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,54,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,41,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32557,27,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32558,40,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32559,58,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32560,22,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [9]:
data = data.drop('fnlwgt', axis='columns')
data

,age,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,...,income,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Unkown,workclass_Without-pay
0,90,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,82,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,66,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,54,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,41,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32557,27,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32558,40,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32559,58,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32560,22,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [10]:
data['education'].unique()

array(['HS-grad', 'Some-college', '7th-8th', '10th', 'Doctorate',
       'Prof-school', 'Bachelors', 'Masters', '11th', 'Assoc-acdm',
       'Assoc-voc', '1st-4th', '5th-6th', '12th', '9th', 'Preschool'],
      dtype=object)

In [11]:
value = 'No-HS'
data['education'] = data['education'].replace({'7th-8th': value, '10th': value, '1st-4th': value, '5th-6th': value, '9th': value, '11th': value, '12th': value})
data['education'].unique()

array(['HS-grad', 'Some-college', 'No-HS', 'Doctorate', 'Prof-school',
       'Bachelors', 'Masters', 'Assoc-acdm', 'Assoc-voc', 'Preschool'],
      dtype=object)

In [12]:
data

,age,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,...,income,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Unkown,workclass_Without-pay
0,90,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,82,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,66,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,54,No-HS,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,41,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32557,27,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32558,40,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32559,58,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32560,22,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [13]:
data['occupation'] = data['occupation'].replace({'?': np.nan})
data

,age,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,...,income,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Unkown,workclass_Without-pay
0,90,HS-grad,9,Widowed,NaN,Not-in-family,White,Female,0,4356,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,82,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,66,Some-college,10,Widowed,NaN,Unmarried,Black,Female,0,4356,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,54,No-HS,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,41,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32557,27,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32558,40,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32559,58,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32560,22,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [14]:
mode = data['occupation'].mode()[0]
data['occupation'] = data['occupation'].fillna(mode)
data

,age,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,...,income,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,workclass_Private,workclass_Self-emp-inc,workclass_Self-emp-not-inc,workclass_State-gov,workclass_Unkown,workclass_Without-pay
0,90,HS-grad,9,Widowed,Prof-specialty,Not-in-family,White,Female,0,4356,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,82,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,66,Some-college,10,Widowed,Prof-specialty,Unmarried,Black,Female,0,4356,...,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,54,No-HS,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
4,41,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32557,27,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32558,40,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,...,1,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32559,58,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32560,22,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,...,0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [15]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)
encoded = encoder.fit_transform(data[['education']])
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['education']), index=data.index)
data = pd.concat([data.drop('education', axis='columns'), encoded_df], axis='columns')
data

,age,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,...,education_Assoc-acdm,education_Assoc-voc,education_Bachelors,education_Doctorate,education_HS-grad,education_Masters,education_No-HS,education_Preschool,education_Prof-school,education_Some-college
0,90,9,Widowed,Prof-specialty,Not-in-family,White,Female,0,4356,40,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,82,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,66,10,Widowed,Prof-specialty,Unmarried,Black,Female,0,4356,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,54,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,41,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32557,27,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32558,40,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32559,58,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32560,22,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [16]:
data['marital.status'].unique()

array(['Widowed', 'Divorced', 'Separated', 'Never-married',
       'Married-civ-spouse', 'Married-spouse-absent', 'Married-AF-spouse'],
      dtype=object)

In [17]:
value = 'Married'
data['marital.status'] = data['marital.status'].replace({'Married-civ-spouse': value, 'Married-spouse-absent': value, 'Married-AF-spouse': value})
data

,age,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,...,education_Assoc-acdm,education_Assoc-voc,education_Bachelors,education_Doctorate,education_HS-grad,education_Masters,education_No-HS,education_Preschool,education_Prof-school,education_Some-college
0,90,9,Widowed,Prof-specialty,Not-in-family,White,Female,0,4356,40,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,82,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,66,10,Widowed,Prof-specialty,Unmarried,Black,Female,0,4356,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
3,54,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
4,41,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32557,27,12,Married,Tech-support,Wife,White,Female,0,0,38,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32558,40,9,Married,Machine-op-inspct,Husband,White,Male,0,0,40,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32559,58,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32560,22,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [18]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

encoded = encoder.fit_transform(data[['marital.status']])

endoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['marital.status']), index=data.index)

data = pd.concat([data.drop('marital.status', axis='columns'), endoded_df], axis='columns')

data

,age,education.num,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,...,education_Masters,education_No-HS,education_Preschool,education_Prof-school,education_Some-college,marital.status_Divorced,marital.status_Married,marital.status_Never-married,marital.status_Separated,marital.status_Widowed
0,90,9,Prof-specialty,Not-in-family,White,Female,0,4356,40,United-States,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1,82,9,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
2,66,10,Prof-specialty,Unmarried,Black,Female,0,4356,40,United-States,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
3,54,4,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,...,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,41,10,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,10,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
32557,27,12,Tech-support,Wife,White,Female,0,0,38,United-States,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
32558,40,9,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
32559,58,9,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32560,22,9,Adm-clerical,Own-child,White,Male,0,0,20,United-States,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [19]:
data['race'].unique()

encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False)

encoded = encoder.fit_transform(data[['race']])

encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['race']), index=data.index)

data = pd.concat([data.drop('race', axis='columns'), encoded_df], axis='columns')

data

,age,education.num,occupation,relationship,sex,capital.gain,capital.loss,hours.per.week,native.country,income,...,marital.status_Divorced,marital.status_Married,marital.status_Never-married,marital.status_Separated,marital.status_Widowed,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,90,9,Prof-specialty,Not-in-family,Female,0,4356,40,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,82,9,Exec-managerial,Not-in-family,Female,0,4356,18,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,66,10,Prof-specialty,Unmarried,Female,0,4356,40,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,54,4,Machine-op-inspct,Unmarried,Female,0,3900,40,United-States,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,41,10,Prof-specialty,Own-child,Female,0,3900,40,United-States,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,10,Protective-serv,Not-in-family,Male,0,0,40,United-States,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32557,27,12,Tech-support,Wife,Female,0,0,38,United-States,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32558,40,9,Machine-op-inspct,Husband,Male,0,0,40,United-States,1,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32559,58,9,Adm-clerical,Unmarried,Female,0,0,40,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
32560,22,9,Adm-clerical,Own-child,Male,0,0,20,United-States,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [20]:
data['sex'] = data['sex'].replace({'Female': 0, 'Male': 1})
data

/var/folders/tl/sxyv3tjs7wlff0fs8dht26pr0000gn/T/ipykernel_27185/3478245929.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['sex'] = data['sex'].replace({'Female': 0, 'Male': 1})

,age,education.num,occupation,relationship,sex,capital.gain,capital.loss,hours.per.week,native.country,income,...,marital.status_Divorced,marital.status_Married,marital.status_Never-married,marital.status_Separated,marital.status_Widowed,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,90,9,Prof-specialty,Not-in-family,0,0,4356,40,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,82,9,Exec-managerial,Not-in-family,0,0,4356,18,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,66,10,Prof-specialty,Unmarried,0,0,4356,40,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,54,4,Machine-op-inspct,Unmarried,0,0,3900,40,United-States,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,41,10,Prof-specialty,Own-child,0,0,3900,40,United-States,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,10,Protective-serv,Not-in-family,1,0,0,40,United-States,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32557,27,12,Tech-support,Wife,0,0,0,38,United-States,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32558,40,9,Machine-op-inspct,Husband,1,0,0,40,United-States,1,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32559,58,9,Adm-clerical,Unmarried,0,0,0,40,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
32560,22,9,Adm-clerical,Own-child,1,0,0,20,United-States,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [21]:
data['native.country'].unique()

array(['United-States', '?', 'Mexico', 'Greece', 'Vietnam', 'China',
       'Taiwan', 'India', 'Philippines', 'Trinadad&Tobago', 'Canada',
       'South', 'Holand-Netherlands', 'Puerto-Rico', 'Poland', 'Iran',
       'England', 'Germany', 'Italy', 'Japan', 'Hong', 'Honduras', 'Cuba',
       'Ireland', 'Cambodia', 'Peru', 'Nicaragua', 'Dominican-Republic',
       'Haiti', 'El-Salvador', 'Hungary', 'Columbia', 'Guatemala',
       'Jamaica', 'Ecuador', 'France', 'Yugoslavia', 'Scotland',
       'Portugal', 'Laos', 'Thailand', 'Outlying-US(Guam-USVI-etc)'],
      dtype=object)

In [22]:
data['native.country'] = data['native.country'].replace({'?': np.nan})
data['native.country'].isnull().sum()

np.int64(583)

In [23]:
data = data.dropna(subset='native.country')
data['native.country'].isnull().sum()

np.int64(0)

In [24]:
data

,age,education.num,occupation,relationship,sex,capital.gain,capital.loss,hours.per.week,native.country,income,...,marital.status_Divorced,marital.status_Married,marital.status_Never-married,marital.status_Separated,marital.status_Widowed,race_Amer-Indian-Eskimo,race_Asian-Pac-Islander,race_Black,race_Other,race_White
0,90,9,Prof-specialty,Not-in-family,0,0,4356,40,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
1,82,9,Exec-managerial,Not-in-family,0,0,4356,18,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
2,66,10,Prof-specialty,Unmarried,0,0,4356,40,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
3,54,4,Machine-op-inspct,Unmarried,0,0,3900,40,United-States,0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
4,41,10,Prof-specialty,Own-child,0,0,3900,40,United-States,0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,10,Protective-serv,Not-in-family,1,0,0,40,United-States,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32557,27,12,Tech-support,Wife,0,0,0,38,United-States,0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32558,40,9,Machine-op-inspct,Husband,1,0,0,40,United-States,1,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32559,58,9,Adm-clerical,Unmarried,0,0,0,40,United-States,0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0
32560,22,9,Adm-clerical,Own-child,1,0,0,20,United-States,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [25]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False, min_frequency=50)
encoded = encoder.fit_transform(data[['native.country']])

encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['native.country']), index=data.index)
data = pd.concat([data.drop('native.country', axis='columns'), encoded_df], axis='columns')

data

,age,education.num,occupation,relationship,sex,capital.gain,capital.loss,hours.per.week,income,workclass_Federal-gov,...,native.country_Japan,native.country_Mexico,native.country_Philippines,native.country_Poland,native.country_Puerto-Rico,native.country_South,native.country_Taiwan,native.country_United-States,native.country_Vietnam,native.country_infrequent_sklearn
0,90,9,Prof-specialty,Not-in-family,0,0,4356,40,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,82,9,Exec-managerial,Not-in-family,0,0,4356,18,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
2,66,10,Prof-specialty,Unmarried,0,0,4356,40,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
3,54,4,Machine-op-inspct,Unmarried,0,0,3900,40,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
4,41,10,Prof-specialty,Own-child,0,0,3900,40,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,10,Protective-serv,Not-in-family,1,0,0,40,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
32557,27,12,Tech-support,Wife,0,0,0,38,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
32558,40,9,Machine-op-inspct,Husband,1,0,0,40,1,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
32559,58,9,Adm-clerical,Unmarried,0,0,0,40,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
32560,22,9,Adm-clerical,Own-child,1,0,0,20,0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [26]:
data['occupation'].unique()

array(['Prof-specialty', 'Exec-managerial', 'Machine-op-inspct',
       'Other-service', 'Adm-clerical', 'Transport-moving', 'Sales',
       'Craft-repair', 'Farming-fishing', 'Tech-support',
       'Protective-serv', 'Handlers-cleaners', 'Armed-Forces',
       'Priv-house-serv'], dtype=object)

In [27]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False, min_frequency=50)
encoded = encoder.fit_transform(data[['occupation']])

encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['occupation']), index=data.index)
data = pd.concat([data.drop('occupation', axis='columns'), encoded_df], axis='columns')

data

,age,education.num,relationship,sex,capital.gain,capital.loss,hours.per.week,income,workclass_Federal-gov,workclass_Local-gov,...,occupation_Handlers-cleaners,occupation_Machine-op-inspct,occupation_Other-service,occupation_Priv-house-serv,occupation_Prof-specialty,occupation_Protective-serv,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,occupation_infrequent_sklearn
0,90,9,Not-in-family,0,0,4356,40,0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
1,82,9,Not-in-family,0,0,4356,18,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,66,10,Unmarried,0,0,4356,40,0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,54,4,Unmarried,0,0,3900,40,0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,41,10,Own-child,0,0,3900,40,0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,10,Not-in-family,1,0,0,40,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
32557,27,12,Wife,0,0,0,38,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
32558,40,9,Husband,1,0,0,40,1,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32559,58,9,Unmarried,0,0,0,40,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32560,22,9,Own-child,1,0,0,20,0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [28]:
encoder = OneHotEncoder(handle_unknown='ignore', sparse_output=False, min_frequency=50)
encoded = encoder.fit_transform(data[['relationship']])

encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(['relationship']), index=data.index)
data = pd.concat([data.drop('relationship', axis='columns'), encoded_df], axis='columns')

data

,age,education.num,sex,capital.gain,capital.loss,hours.per.week,income,workclass_Federal-gov,workclass_Local-gov,workclass_Never-worked,...,occupation_Sales,occupation_Tech-support,occupation_Transport-moving,occupation_infrequent_sklearn,relationship_Husband,relationship_Not-in-family,relationship_Other-relative,relationship_Own-child,relationship_Unmarried,relationship_Wife
0,90,9,0,0,4356,40,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1,82,9,0,0,4356,18,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,66,10,0,0,4356,40,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,54,4,0,0,3900,40,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,41,10,0,0,3900,40,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32556,22,10,1,0,0,40,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
32557,27,12,0,0,0,38,0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
32558,40,9,1,0,0,40,1,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
32559,58,9,0,0,0,40,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
32560,22,9,1,0,0,20,0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0

In [29]:
data.isnull().sum()

age                            0
education.num                  0
sex                            0
capital.gain                   0
capital.loss                   0
                              ..
relationship_Not-in-family     0
relationship_Other-relative    0
relationship_Own-child         0
relationship_Unmarried         0
relationship_Wife              0
Length: 78, dtype: int64