In [1]:
import pandas as pd
import numpy as np

In [2]:
link = "/Users/maxkucher/preprocessing/mlops/movies_and_shows/data.csv"
data = pd.read_csv(link)
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [3]:
data.isnull().sum()

show_id            0
type               0
title              0
director        2634
cast             825
country          831
date_added        10
release_year       0
rating             4
duration           3
listed_in          0
description        0
dtype: int64

In [4]:
data["director"] = data["director"].fillna("Unknown")
data["cast"] = data["cast"].fillna("Unknown")
data["country"] = data["country"].fillna("Unknown")

In [5]:
data.isnull().sum()

show_id          0
type             0
title            0
director         0
cast             0
country          0
date_added      10
release_year     0
rating           4
duration         3
listed_in        0
description      0
dtype: int64

In [6]:
data = data.dropna(subset=["date_added"])
data = data.dropna(subset=["rating"])
data = data.dropna(subset=["duration"])

In [7]:
data.isnull().sum()

show_id         0
type            0
title           0
director        0
cast            0
country         0
date_added      0
release_year    0
rating          0
duration        0
listed_in       0
description     0
dtype: int64

In [8]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,Unknown,Unknown,Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,Unknown,Unknown,Unknown,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [9]:
data["type"].unique()

array(['Movie', 'TV Show'], dtype=object)

In [10]:
data["type"] = data["type"].replace({"Movie": 0, "TV Show": 1})

/var/folders/tl/sxyv3tjs7wlff0fs8dht26pr0000gn/T/ipykernel_68677/3156575974.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data["type"] = data["type"].replace({"Movie": 0, "TV Show": 1})

In [11]:
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,1,Zombie Dumb,Unknown,Unknown,Unknown,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [12]:
data["country"] = data["country"].str.split(",").str[0].str.strip()
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,1,Zombie Dumb,Unknown,Unknown,Unknown,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [13]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False, min_frequency=20)
encoded = encoder.fit_transform(data[["country"]])
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(["country"]), index=data.index)

data = pd.concat([data.drop("country", axis="columns"), encoded_df], axis="columns")
data

,show_id,type,title,director,cast,date_added,release_year,rating,duration,listed_in,...,country_South Korea,country_Spain,country_Taiwan,country_Thailand,country_Turkey,country_United Arab Emirates,country_United Kingdom,country_United States,country_Unknown,country_infrequent_sklearn
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,"September 25, 2021",2020,PG-13,90 min,Documentaries,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...","September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...","September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...","September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...","November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8803,s8804,1,Zombie Dumb,Unknown,Unknown,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...","November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...","January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...","March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
data["date_added"] = pd.to_datetime(data["date_added"], errors='coerce')
data

,show_id,type,title,director,cast,date_added,release_year,rating,duration,listed_in,...,country_South Korea,country_Spain,country_Taiwan,country_Thailand,country_Turkey,country_United Arab Emirates,country_United Kingdom,country_United States,country_Unknown,country_infrequent_sklearn
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,2021-09-25,2020,PG-13,90 min,Documentaries,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",2021-09-24,2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,2021-09-24,2021,TV-MA,1 Season,"Docuseries, Reality TV",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",2021-09-24,2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",2019-11-20,2007,R,158 min,"Cult Movies, Dramas, Thrillers",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8803,s8804,1,Zombie Dumb,Unknown,Unknown,2019-07-01,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",2019-11-01,2009,R,88 min,"Comedies, Horror Movies",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",2020-01-11,2006,PG,88 min,"Children & Family Movies, Comedies",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",2019-03-02,2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [15]:
data['year'] = data["date_added"].dt.year
data['month'] = data["date_added"].dt.month
data = data.drop("date_added", axis="columns")
data

,show_id,type,title,director,cast,release_year,rating,duration,listed_in,description,...,country_Taiwan,country_Thailand,country_Turkey,country_United Arab Emirates,country_United Kingdom,country_United States,country_Unknown,country_infrequent_sklearn,year,month
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2021.0,9.0
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2021.0,9.0
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2021.0,9.0
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2021.0,9.0
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2021.0,9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2019.0,11.0
8803,s8804,1,Zombie Dumb,Unknown,Unknown,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2019.0,7.0
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2019.0,11.0
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2020.0,1.0
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2019.0,3.0

In [16]:
# !IMPORTANT - Cycle endocing 

data["month_sin"] = np.sin(2 * np.pi * data["month"] / 12)
data["month_cos"] = np.cos(2 * np.pi * data["month"] / 12)
data = data.drop('month', axis="columns")
data

,show_id,type,title,director,cast,release_year,rating,duration,listed_in,description,...,country_Thailand,country_Turkey,country_United Arab Emirates,country_United Kingdom,country_United States,country_Unknown,country_infrequent_sklearn,year,month_sin,month_cos
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2021.0,-1.0,-1.836970e-16
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2021.0,-1.0,-1.836970e-16
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2021.0,-1.0,-1.836970e-16
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2021.0,-1.0,-1.836970e-16
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2021.0,-1.0,-1.836970e-16
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2019.0,-0.5,8.660254e-01
8803,s8804,1,Zombie Dumb,Unknown,Unknown,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2019.0,-0.5,-8.660254e-01
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2019.0,-0.5,8.660254e-01
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,2020.0,0.5,8.660254e-01
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2019.0,1.0,6.123234e-17

In [17]:
data["rating"].unique()

array(['PG-13', 'TV-MA', 'PG', 'TV-14', 'TV-PG', 'TV-Y', 'TV-Y7', 'R',
       'TV-G', 'G', 'NC-17', 'NR', 'TV-Y7-FV', 'UR'], dtype=object)

In [18]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(handle_unknown="ignore", sparse_output=False, min_frequency=20)

encoded = encoder.fit_transform(data[["rating"]])
encoded_df = pd.DataFrame(encoded, columns=encoder.get_feature_names_out(["rating"]), index=data.index)
data = pd.concat([data, encoded_df], axis="columns")
data

,show_id,type,title,director,cast,release_year,rating,duration,listed_in,description,...,rating_PG,rating_PG-13,rating_R,rating_TV-14,rating_TV-G,rating_TV-MA,rating_TV-PG,rating_TV-Y,rating_TV-Y7,rating_infrequent_sklearn
0,s1,0,Dick Johnson Is Dead,Kirsten Johnson,Unknown,2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm...",...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,s2,1,Blood & Water,Unknown,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
2,s3,1,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,s4,1,Jailbirds New Orleans,Unknown,Unknown,2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,s5,1,Kota Factory,Unknown,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,0,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8803,s8804,1,Zombie Dumb,Unknown,Unknown,2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
8804,s8805,0,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8805,s8806,0,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8806,s8807,0,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [19]:
def parse_duration(value: str):
    if pd.isna(value):
        return np.nan, np.nan
    
    value = value.lower()
    
    if "min" in value:
        minutes = int(value.replace("min", "").strip())
        return minutes, 0

    if "season" in value:
        seasons = int(value.replace("seasons", "").replace("season", "").strip())
        return 0, seasons
    
    return np.nan, np.nan


data[["duration_minutes", "duration_seasons"]] = (data["duration"].apply(parse_duration).apply(pd.Series))
data = data.drop("duration", axis="columns")

In [20]:
data = data.drop(["show_id", "title", "director", "cast"], axis="columns")
data

,type,release_year,rating,listed_in,description,country_Argentina,country_Australia,country_Brazil,country_Canada,country_Chile,...,rating_R,rating_TV-14,rating_TV-G,rating_TV-MA,rating_TV-PG,rating_TV-Y,rating_TV-Y7,rating_infrequent_sklearn,duration_minutes,duration_seasons
0,0,2020,PG-13,Documentaries,"As her father nears the end of his life, filmm...",0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,90,0
1,1,2021,TV-MA,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t...",0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,2
2,1,2021,TV-MA,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,1
3,1,2021,TV-MA,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo...",0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,1
4,1,2021,TV-MA,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,0,2007,R,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a...",0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,158,0
8803,1,2018,TV-Y7,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g...",0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,2
8804,0,2009,R,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88,0
8805,0,2006,PG,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero...",0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88,0
8806,0,2015,TV-14,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,111,0

In [21]:
data["listed_in"].unique()

array(['Documentaries', 'International TV Shows, TV Dramas, TV Mysteries',
       'Crime TV Shows, International TV Shows, TV Action & Adventure',
       'Docuseries, Reality TV',
       'International TV Shows, Romantic TV Shows, TV Comedies',
       'TV Dramas, TV Horror, TV Mysteries', 'Children & Family Movies',
       'Dramas, Independent Movies, International Movies',
       'British TV Shows, Reality TV', 'Comedies, Dramas',
       'Crime TV Shows, Docuseries, International TV Shows',
       'Dramas, International Movies',
       'Children & Family Movies, Comedies',
       'British TV Shows, Crime TV Shows, Docuseries',
       'TV Comedies, TV Dramas', 'Documentaries, International Movies',
       'Crime TV Shows, Spanish-Language TV Shows, TV Dramas',
       'Thrillers',
       'International TV Shows, Spanish-Language TV Shows, TV Action & Adventure',
       'International TV Shows, TV Action & Adventure, TV Dramas',
       'Comedies, International Movies',
       'Comedies, International Movies, Romantic Movies',
       'Docuseries, International TV Shows, Reality TV',
       'Comedies, International Movies, Music & Musicals', 'Comedies',
       'Horror Movies, Sci-Fi & Fantasy', 'TV Comedies',
       'British TV Shows, International TV Shows, TV Comedies',
       'International TV Shows, TV Dramas, TV Thrillers', "Kids' TV",
       'Dramas, International Movies, Thrillers',
       'Action & Adventure, Dramas, International Movies',
       "Kids' TV, TV Comedies", 'Action & Adventure, Dramas',
       "Kids' TV, TV Sci-Fi & Fantasy",
       'Action & Adventure, Classic Movies, Dramas',
       'Dramas, Horror Movies, Thrillers',
       'Action & Adventure, Horror Movies, Thrillers',
       'Action & Adventure', 'Dramas, Thrillers',
       'International TV Shows, TV Dramas',
       'International TV Shows, TV Dramas, TV Sci-Fi & Fantasy',
       'Action & Adventure, Anime Features, International Movies',
       'Reality TV', 'Docuseries, International TV Shows',
       'Documentaries, International Movies, Sports Movies',
       'International TV Shows, Reality TV, Romantic TV Shows',
       'British TV Shows, Docuseries, International TV Shows',
       'Anime Series, International TV Shows',
       'Comedies, Dramas, International Movies',
       'Crime TV Shows, TV Comedies, TV Dramas',
       'Action & Adventure, Comedies, Dramas', "Anime Series, Kids' TV",
       'International Movies, Thrillers', "Kids' TV, Korean TV Shows",
       'Documentaries, Sports Movies', 'Sci-Fi & Fantasy, Thrillers',
       'Dramas, International Movies, Romantic Movies',
       'Documentaries, Music & Musicals',
       "Kids' TV, TV Comedies, TV Sci-Fi & Fantasy",
       "British TV Shows, Kids' TV", 'Docuseries, Science & Nature TV',
       'Children & Family Movies, Dramas',
       "Kids' TV, TV Dramas, Teen TV Shows",
       'Crime TV Shows, International TV Shows, Spanish-Language TV Shows',
       'Docuseries, International TV Shows, Spanish-Language TV Shows',
       'Dramas', 'Comedies, Romantic Movies', 'Dramas, Romantic Movies',
       'Comedies, Dramas, Independent Movies',
       'Crime TV Shows, TV Action & Adventure, TV Comedies',
       'Children & Family Movies, Music & Musicals',
       'Action & Adventure, Classic Movies, Cult Movies',
       'International TV Shows, TV Action & Adventure, TV Comedies',
       'Action & Adventure, Sci-Fi & Fantasy',
       'Action & Adventure, Comedies', 'Classic Movies, Comedies, Dramas',
       'Comedies, Cult Movies', 'Comedies, Cult Movies, Music & Musicals',
       'Comedies, Music & Musicals', 'TV Shows',
       'Action & Adventure, International Movies',
       'Anime Series, International TV Shows, Teen TV Shows',
       'Action & Adventure, Children & Family Movies, Cult Movies',
       'Comedies, Dramas, Romantic Movies',
       'Comedies, Cult Movies, Sci-Fi & Fantasy',
       'Classic Movies, Dramas',
       'Action & Adventure, Children & Family Movies, Comedies',
       'Dramas, Faith & Spirituality', 'Documentaries, LGBTQ Movies',
       'Action & Adventure, Classic Movies', 'Docuseries',
       'International TV Shows, TV Comedies',
       'Dramas, Independent Movies',
       'Action & Adventure, Comedies, International Movies',
       'International TV Shows, Spanish-Language TV Shows, TV Dramas',
       'Crime TV Shows, International TV Shows, TV Dramas',
       'Action & Adventure, Horror Movies, International Movies',
       'Comedies, International Movies, Sci-Fi & Fantasy',
       'Action & Adventure, International Movies, Music & Musicals',
       'Dramas, International Movies, Music & Musicals',
       'Horror Movies, International Movies', 'Reality TV, Teen TV Shows',
       'Crime TV Shows, TV Dramas, TV Mysteries',
       'International TV Shows, Reality TV',
       'International TV Shows, TV Comedies, TV Dramas',
       'Dramas, Independent Movies, Romantic Movies', 'Horror Movies',
       'Documentaries, LGBTQ Movies, Sports Movies',
       'Horror Movies, International Movies, Thrillers',
       'Action & Adventure, Anime Features',
       'TV Dramas, TV Mysteries, TV Sci-Fi & Fantasy',
       'International TV Shows, Spanish-Language TV Shows, TV Comedies',
       'Children & Family Movies, Comedies, Music & Musicals',
       'Comedies, Independent Movies',
       'Anime Series, International TV Shows, Romantic TV Shows',
       'Classic Movies, Dramas, Independent Movies',
       'International TV Shows, Romantic TV Shows, Spanish-Language TV Shows',
       'International TV Shows, TV Dramas, Teen TV Shows',
       'Stand-Up Comedy',
       'Action & Adventure, Anime Features, Children & Family Movies',
       'International TV Shows, Romantic TV Shows, TV Dramas',
       'International Movies, Music & Musicals',
       'TV Action & Adventure, TV Dramas, TV Mysteries',
       'Horror Movies, Independent Movies, International Movies',
       'Comedies, Cult Movies, International Movies',
       'Classic Movies, Dramas, International Movies', 'Movies',
       'Crime TV Shows, Docuseries',
       'Children & Family Movies, Comedies, Sci-Fi & Fantasy',
       'Anime Series, International TV Shows, TV Thrillers',
       'Action & Adventure, Horror Movies, Sci-Fi & Fantasy',
       'Classic Movies, Comedies, Cult Movies',
       'TV Dramas, Teen TV Shows',
       'Action & Adventure, Sci-Fi & Fantasy, Thrillers',
       'Children & Family Movies, Comedies, Dramas',
       'Dramas, Sports Movies',
       'Action & Adventure, Dramas, Sci-Fi & Fantasy',
       'Action & Adventure, Comedies, Cult Movies',
       'Dramas, Independent Movies, Thrillers',
       'TV Dramas, TV Sci-Fi & Fantasy',
       'Action & Adventure, International Movies, Thrillers',
       'British TV Shows, International TV Shows, Reality TV',
       'TV Action & Adventure, TV Dramas, Teen TV Shows', 'Anime Series',
       'Crime TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Crime TV Shows, International TV Shows, TV Comedies',
       'Stand-Up Comedy & Talk Shows, TV Comedies',
       'Classic & Cult TV, TV Action & Adventure, TV Dramas',
       'Children & Family Movies, Sports Movies',
       'TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Anime Series, Stand-Up Comedy & Talk Shows', 'TV Dramas',
       'Anime Features, Children & Family Movies, International Movies',
       'Classic & Cult TV, Crime TV Shows, International TV Shows',
       'Crime TV Shows, International TV Shows, Romantic TV Shows',
       'Horror Movies, LGBTQ Movies',
       'Action & Adventure, Dramas, Romantic Movies',
       'Documentaries, International Movies, Music & Musicals',
       'TV Comedies, TV Dramas, Teen TV Shows',
       'Children & Family Movies, Comedies, Sports Movies',
       'Children & Family Movies, Dramas, International Movies',
       'Comedies, Documentaries, International Movies',
       'Romantic TV Shows, TV Dramas',
       'Anime Series, TV Horror, TV Thrillers',
       'International Movies, Romantic Movies',
       'TV Action & Adventure, TV Dramas, TV Sci-Fi & Fantasy',
       "Kids' TV, Korean TV Shows, TV Comedies",
       'British TV Shows, Crime TV Shows, International TV Shows',
       'Crime TV Shows, TV Horror, TV Mysteries',
       'Docuseries, International TV Shows, Science & Nature TV',
       'British TV Shows, International TV Shows, TV Dramas',
       "Kids' TV, TV Action & Adventure, TV Sci-Fi & Fantasy",
       'International Movies, Romantic Movies, Thrillers',
       'Action & Adventure, Cult Movies, International Movies',
       'Action & Adventure, Comedies, Sci-Fi & Fantasy',
       "International TV Shows, Kids' TV, TV Mysteries",
       'Action & Adventure, Thrillers',
       'Dramas, Faith & Spirituality, International Movies',
       'Action & Adventure, Classic Movies, Comedies',
       'Action & Adventure, Comedies, Sports Movies',
       'Action & Adventure, Children & Family Movies, Classic Movies',
       'Action & Adventure, Children & Family Movies, Dramas',
       'Horror Movies, Thrillers', 'Action & Adventure, Romantic Movies',
       'Dramas, Romantic Movies, Sci-Fi & Fantasy',
       'Dramas, Music & Musicals, Romantic Movies',
       'Anime Series, Crime TV Shows, International TV Shows',
       'Reality TV, Romantic TV Shows',
       'International Movies, Music & Musicals, Romantic Movies',
       'Reality TV, TV Action & Adventure, TV Mysteries',
       'Crime TV Shows, TV Dramas',
       'International TV Shows, Reality TV, Spanish-Language TV Shows',
       'Crime TV Shows, TV Dramas, TV Thrillers',
       'British TV Shows, Docuseries',
       'International TV Shows, Korean TV Shows, TV Comedies',
       'Action & Adventure, Anime Features, Classic Movies',
       'TV Action & Adventure, TV Dramas, TV Horror',
       'Crime TV Shows, International TV Shows, TV Thrillers',
       'Anime Series, Crime TV Shows, TV Horror',
       'Anime Features, Documentaries', 'Comedies, Horror Movies',
       'International TV Shows, Spanish-Language TV Shows, Stand-Up Comedy & Talk Shows',
       'Children & Family Movies, Documentaries, International Movies',
       'Romantic TV Shows, TV Comedies, TV Dramas',
       'Dramas, Faith & Spirituality, Romantic Movies',
       'Dramas, Independent Movies, LGBTQ Movies',
       'Comedies, Independent Movies, LGBTQ Movies',
       'Action & Adventure, Cult Movies, Sci-Fi & Fantasy',
       'Cult Movies, Horror Movies',
       'Action & Adventure, Dramas, Sports Movies',
       'Anime Series, Romantic TV Shows, Teen TV Shows',
       'Dramas, International Movies, LGBTQ Movies',
       'Dramas, Romantic Movies, Thrillers',
       'Children & Family Movies, Dramas, Faith & Spirituality',
       'Dramas, International Movies, Sports Movies',
       'Action & Adventure, Horror Movies',
       'Documentaries, International Movies, LGBTQ Movies',
       'Dramas, Independent Movies, Sci-Fi & Fantasy',
       'Comedies, Independent Movies, International Movies',
       'Reality TV, TV Horror, TV Thrillers',
       'TV Action & Adventure, TV Horror, TV Sci-Fi & Fantasy',
       'International TV Shows, TV Horror, TV Sci-Fi & Fantasy',
       'Independent Movies, International Movies, Thrillers',
       'Independent Movies, Thrillers', 'Documentaries, Dramas',
       'Action & Adventure, Sports Movies',
       'Dramas, International Movies, Sci-Fi & Fantasy',
       'Comedies, Independent Movies, Romantic Movies',
       'Horror Movies, Romantic Movies, Sci-Fi & Fantasy',
       'International TV Shows, Stand-Up Comedy & Talk Shows',
       'Action & Adventure, Anime Features, Horror Movies',
       'Cult Movies, Dramas, Music & Musicals', 'TV Dramas, TV Thrillers',
       'Crime TV Shows, International TV Shows, Korean TV Shows',
       'TV Horror, TV Mysteries, TV Thrillers',
       'Comedies, Horror Movies, International Movies',
       'Crime TV Shows, Docuseries, TV Mysteries',
       'Comedies, International Movies, Sports Movies',
       'Classic Movies, Music & Musicals',
       'Reality TV, TV Comedies, TV Horror',
       'Children & Family Movies, Faith & Spirituality, Music & Musicals',
       'International TV Shows, Korean TV Shows, Stand-Up Comedy & Talk Shows',
       'Dramas, Music & Musicals',
       'Docuseries, Science & Nature TV, TV Action & Adventure',
       "British TV Shows, Kids' TV, TV Dramas",
       'International TV Shows, Korean TV Shows, Romantic TV Shows',
       'Horror Movies, Independent Movies',
       "Anime Series, Kids' TV, TV Action & Adventure",
       'Comedies, Dramas, Music & Musicals', 'TV Horror, Teen TV Shows',
       'Comedies, LGBTQ Movies, Thrillers',
       'Docuseries, Reality TV, Science & Nature TV',
       'Crime TV Shows, Spanish-Language TV Shows, TV Action & Adventure',
       'Romantic TV Shows, Teen TV Shows', 'TV Comedies, Teen TV Shows',
       'Romantic TV Shows, TV Dramas, Teen TV Shows',
       'Children & Family Movies, Sci-Fi & Fantasy',
       'Romantic TV Shows, TV Action & Adventure, TV Dramas',
       'Comedies, International Movies, LGBTQ Movies',
       'Dramas, Sci-Fi & Fantasy', "Kids' TV, TV Thrillers",
       'TV Action & Adventure, TV Comedies, TV Sci-Fi & Fantasy',
       'British TV Shows, Romantic TV Shows, TV Dramas',
       'Anime Series, International TV Shows, Spanish-Language TV Shows',
       'Docuseries, TV Comedies',
       'Comedies, Romantic Movies, Sports Movies',
       'TV Action & Adventure, TV Comedies, TV Dramas',
       'Children & Family Movies, Dramas, Sports Movies',
       'Action & Adventure, Dramas, Independent Movies',
       'Spanish-Language TV Shows, TV Dramas', 'Dramas, LGBTQ Movies',
       'TV Horror, TV Mysteries, TV Sci-Fi & Fantasy',
       'Action & Adventure, Dramas, Faith & Spirituality',
       'International TV Shows, TV Mysteries, TV Thrillers',
       'British TV Shows, Classic & Cult TV, International TV Shows',
       'Action & Adventure, Comedies, Independent Movies',
       'Music & Musicals', "British TV Shows, Kids' TV, TV Comedies",
       'Docuseries, Spanish-Language TV Shows',
       'Dramas, Independent Movies, Sports Movies',
       'TV Dramas, TV Mysteries, TV Thrillers',
       'Comedies, LGBTQ Movies, Music & Musicals',
       'International TV Shows, TV Action & Adventure, TV Mysteries',
       "Kids' TV, TV Comedies, Teen TV Shows",
       'International TV Shows, TV Dramas, TV Horror',
       'Comedies, International Movies, Thrillers',
       'Classic & Cult TV, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'International TV Shows, TV Horror, TV Mysteries',
       'Children & Family Movies, Documentaries',
       'Music & Musicals, Romantic Movies', 'Romantic Movies',
       'Children & Family Movies, Classic Movies, Comedies',
       'TV Action & Adventure, TV Dramas',
       'Dramas, LGBTQ Movies, Romantic Movies',
       'Children & Family Movies, Comedies, Romantic Movies',
       'Comedies, Sports Movies', 'International Movies',
       'International TV Shows, Romantic TV Shows, TV Mysteries',
       'Stand-Up Comedy & Talk Shows',
       'Action & Adventure, International Movies, Romantic Movies',
       'Reality TV, TV Comedies',
       'Cult Movies, Dramas, International Movies', "Kids' TV, TV Dramas",
       'Crime TV Shows, International TV Shows, TV Mysteries',
       'Action & Adventure, Sci-Fi & Fantasy, Sports Movies',
       'TV Dramas, TV Sci-Fi & Fantasy, TV Thrillers',
       'Romantic TV Shows, TV Dramas, TV Sci-Fi & Fantasy',
       'Docuseries, TV Sci-Fi & Fantasy',
       'Anime Features, International Movies',
       "British TV Shows, Classic & Cult TV, Kids' TV",
       'British TV Shows, Reality TV, Romantic TV Shows',
       'Documentaries, Faith & Spirituality, International Movies',
       "Kids' TV, Reality TV, TV Dramas", 'LGBTQ Movies, Thrillers',
       'TV Action & Adventure, TV Mysteries, TV Sci-Fi & Fantasy',
       'Reality TV, Science & Nature TV',
       "Kids' TV, TV Action & Adventure, TV Comedies",
       'International TV Shows, Romantic TV Shows, TV Action & Adventure',
       'Children & Family Movies, Dramas, Independent Movies',
       'Comedies, Music & Musicals, Romantic Movies',
       'International TV Shows, Korean TV Shows, Reality TV',
       'Classic & Cult TV, TV Dramas, TV Sci-Fi & Fantasy',
       'Anime Features, Children & Family Movies',
       'Action & Adventure, International Movies, Sci-Fi & Fantasy',
       'Crime TV Shows, TV Action & Adventure, TV Dramas',
       'Classic & Cult TV, TV Action & Adventure, TV Horror',
       'International TV Shows, Korean TV Shows, TV Dramas',
       'International TV Shows, TV Action & Adventure, TV Horror',
       'Action & Adventure, Comedies, Romantic Movies',
       'International TV Shows, Korean TV Shows, TV Action & Adventure',
       "Classic & Cult TV, Kids' TV, TV Action & Adventure",
       'Anime Series, International TV Shows, TV Horror',
       'International TV Shows, Korean TV Shows, TV Horror',
       'Children & Family Movies, Comedies, International Movies',
       'International Movies, Sci-Fi & Fantasy',
       'International Movies, Sci-Fi & Fantasy, Thrillers',
       'Children & Family Movies, Dramas, Romantic Movies',
       'Anime Series, Romantic TV Shows',
       'Comedies, Dramas, LGBTQ Movies',
       'British TV Shows, International TV Shows, TV Action & Adventure',
       'Docuseries, Science & Nature TV, TV Comedies',
       'International TV Shows, Stand-Up Comedy & Talk Shows, TV Comedies',
       'Children & Family Movies, Dramas, Music & Musicals',
       'Action & Adventure, Independent Movies, International Movies',
       'Action & Adventure, Children & Family Movies, Sci-Fi & Fantasy',
       'Horror Movies, Independent Movies, Sci-Fi & Fantasy',
       'TV Dramas, TV Sci-Fi & Fantasy, Teen TV Shows',
       'Anime Features, International Movies, Sci-Fi & Fantasy',
       'Dramas, Independent Movies, Music & Musicals',
       "Kids' TV, TV Comedies, TV Dramas",
       'Children & Family Movies, Documentaries, Sports Movies',
       'Independent Movies, Sci-Fi & Fantasy, Thrillers',
       'Anime Features, Music & Musicals, Sci-Fi & Fantasy',
       'TV Comedies, TV Dramas, TV Sci-Fi & Fantasy',
       'Crime TV Shows, TV Action & Adventure',
       'Comedies, Faith & Spirituality, Romantic Movies',
       "Kids' TV, TV Action & Adventure",
       'Action & Adventure, Independent Movies',
       'International TV Shows, Reality TV, TV Comedies',
       'Docuseries, Reality TV, Teen TV Shows',
       'Crime TV Shows, International TV Shows, Reality TV',
       'Anime Series, Teen TV Shows',
       'Crime TV Shows, Romantic TV Shows, TV Dramas',
       'Anime Features, Romantic Movies',
       'Horror Movies, Sci-Fi & Fantasy, Thrillers',
       'International TV Shows, TV Comedies, TV Sci-Fi & Fantasy',
       'International TV Shows, Romantic TV Shows',
       'Anime Features, Music & Musicals',
       'Anime Features, International Movies, Romantic Movies',
       'International TV Shows, Romantic TV Shows, Teen TV Shows',
       'Docuseries, Stand-Up Comedy & Talk Shows',
       'Horror Movies, Independent Movies, Thrillers',
       'TV Action & Adventure, TV Comedies, TV Horror',
       'Documentaries, Stand-Up Comedy',
       "Kids' TV, Spanish-Language TV Shows",
       "British TV Shows, Kids' TV, TV Thrillers",
       "Kids' TV, TV Action & Adventure, TV Dramas",
       'Anime Series, Crime TV Shows',
       'Dramas, Sci-Fi & Fantasy, Thrillers',
       'TV Comedies, TV Dramas, TV Horror',
       'Children & Family Movies, Comedies, LGBTQ Movies',
       'International TV Shows, TV Action & Adventure, TV Sci-Fi & Fantasy',
       'Docuseries, TV Dramas',
       'Horror Movies, International Movies, Romantic Movies',
       'Crime TV Shows, Docuseries, Science & Nature TV',
       'International Movies, Music & Musicals, Thrillers',
       "Kids' TV, Spanish-Language TV Shows, Teen TV Shows",

In [22]:
data["genres"] = data["listed_in"].str.split(',').apply(lambda x: [g.strip() for g in x])
data = data.drop("listed_in", axis="columns")
data

,type,release_year,rating,description,country_Argentina,country_Australia,country_Brazil,country_Canada,country_Chile,country_China,...,rating_TV-14,rating_TV-G,rating_TV-MA,rating_TV-PG,rating_TV-Y,rating_TV-Y7,rating_infrequent_sklearn,duration_minutes,duration_seasons,genres
0,0,2020,PG-13,"As her father nears the end of his life, filmm...",0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,90,0,[Documentaries]
1,1,2021,TV-MA,"After crossing paths at a party, a Cape Town t...",0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,2,"[International TV Shows, TV Dramas, TV Mysteries]"
2,1,2021,TV-MA,To protect his family from a powerful drug lor...,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,1,"[Crime TV Shows, International TV Shows, TV Ac..."
3,1,2021,TV-MA,"Feuds, flirtations and toilet talk go down amo...",0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,1,"[Docuseries, Reality TV]"
4,1,2021,TV-MA,In a city of coaching centers known to train I...,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0,2,"[International TV Shows, Romantic TV Shows, TV..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,0,2007,R,"A political cartoonist, a crime reporter and a...",0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,158,0,"[Cult Movies, Dramas, Thrillers]"
8803,1,2018,TV-Y7,"While living alone in a spooky town, a young g...",0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0,2,"[Kids' TV, Korean TV Shows, TV Comedies]"
8804,0,2009,R,Looking to survive in a world taken over by zo...,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88,0,"[Comedies, Horror Movies]"
8805,0,2006,PG,"Dragged from civilian life, a former superhero...",0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,88,0,"[Children & Family Movies, Comedies]"
8806,0,2015,TV-14,A scrappy but poor boy worms his way into a ty...,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,111,0,"[Dramas, International Movies, Music & Musicals]"

In [23]:
from sklearn.preprocessing import MultiLabelBinarizer

mlb = MultiLabelBinarizer()
genres_encoded = mlb.fit_transform(data["genres"])
genres_df = pd.DataFrame(genres_encoded, columns=[f"column_{g}" for g in mlb.classes_], index=data.index)
data = pd.concat([data.drop("genres", axis="columns"), genres_df], axis="columns")
data

,type,release_year,rating,description,country_Argentina,country_Australia,country_Brazil,country_Canada,country_Chile,country_China,...,column_TV Action & Adventure,column_TV Comedies,column_TV Dramas,column_TV Horror,column_TV Mysteries,column_TV Sci-Fi & Fantasy,column_TV Shows,column_TV Thrillers,column_Teen TV Shows,column_Thrillers
0,0,2020,PG-13,"As her father nears the end of his life, filmm...",0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,1,2021,TV-MA,"After crossing paths at a party, a Cape Town t...",0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,1,0,0,0,0,0
2,1,2021,TV-MA,To protect his family from a powerful drug lor...,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
3,1,2021,TV-MA,"Feuds, flirtations and toilet talk go down amo...",0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,1,2021,TV-MA,In a city of coaching centers known to train I...,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,0,2007,R,"A political cartoonist, a crime reporter and a...",0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
8803,1,2018,TV-Y7,"While living alone in a spooky town, a young g...",0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
8804,0,2009,R,Looking to survive in a world taken over by zo...,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
8805,0,2006,PG,"Dragged from civilian life, a former superhero...",0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
8806,0,2015,TV-14,A scrappy but poor boy worms his way into a ty...,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [24]:
len(data.columns)

102

In [25]:
data = data.drop("description", axis='columns')
data

,type,release_year,rating,country_Argentina,country_Australia,country_Brazil,country_Canada,country_Chile,country_China,country_Colombia,...,column_TV Action & Adventure,column_TV Comedies,column_TV Dramas,column_TV Horror,column_TV Mysteries,column_TV Sci-Fi & Fantasy,column_TV Shows,column_TV Thrillers,column_Teen TV Shows,column_Thrillers
0,0,2020,PG-13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
1,1,2021,TV-MA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,1,0,1,0,0,0,0,0
2,1,2021,TV-MA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1,0,0,0,0,0,0,0,0,0
3,1,2021,TV-MA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
4,1,2021,TV-MA,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8802,0,2007,R,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,1
8803,1,2018,TV-Y7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,1,0,0,0,0,0,0,0,0
8804,0,2009,R,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
8805,0,2006,PG,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0
8806,0,2015,TV-14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0,0,0,0,0,0,0,0

In [30]:
data.isnull().sum()[data.isnull().sum() > 0]

year         88
month_sin    88
month_cos    88
dtype: int64